# Generated by Django 3.2.8 on 2022-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='text_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
